# Must be unique in a given SonarQube instance
sonar.projectKey=webtek

# This is the name and version displayed in the SonarQube UI.
sonar.projectName=Webtek
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# We set this to the current directory to scan all files.
sonar.sources=.

# Exclude directories or files that should not be analyzed (e.g., external libraries or assets)
sonar.exclusions=assets/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Specify the language if necessary, though SonarQube usually detects HTML, CSS, and JS automatically.
# sonar.language=js,html,css
